name: Deploy AWS CDK OPC

#contrls when the action will run

on:
  #push:
     #branches: [ main ]
     #branches: [ master ]
  #pull_request
     #branches: [ main ]
  
  #allows you to run this workflow manually from the actions tab
  workflow_dispatch:
 
permissions:
  id-token: write
jobs:
 aws_cdk:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-region: eu-north-1
      role-to-assume: arn:aws:iam::954976321623:role/GitHubRole
      role-session-name: samplerolesession
